[pytest]
testpaths = tests
python_files = test_*.py
asyncio_mode = auto
addopts = --cov=app.api.v1 --cov=app.crud --cov=app.api.deps --cov=app.services --cov=app.core --cov=app.utils --cov-report=term-missing --cov-report=xml:coverage.xml --cov-fail-under=70
