import { BlogPost } from '../services/types';

export const mockPosts: BlogPost[] = [
  {
    id: '1',
    title: 'Building a Full-Stack Portfolio with React and FastAPI',
    slug: 'building-fullstack-portfolio',
    excerpt:
      'Learn how to create a modern portfolio website using React, TypeScript, FastAPI, and PostgreSQL. Complete guide with code examples.',
    content: 'Full content here...',
    cover_image: '',
    tags: ['react', 'fastapi', 'python', 'typescript'],
    published: true,
    is_published: true,
    is_featured: true,
    read_time: 10,
    reading_time: 10,
    view_count: 250,
    views: 250,
    created_at: '2025-01-15T00:00:00Z',
    updated_at: '2025-01-15T00:00:00Z',
    published_at: '2025-01-15T00:00:00Z',
  },
  {
    id: '2',
    title: 'Getting Started with Docker and Kubernetes',
    slug: 'docker-kubernetes-guide',
    excerpt:
      'A comprehensive introduction to containerization with Docker and orchestration with Kubernetes for modern applications.',
    content: 'Full content here...',
    cover_image: '',
    tags: ['docker', 'kubernetes', 'devops'],
    published: true,
    is_published: true,
    is_featured: true,
    read_time: 15,
    reading_time: 15,
    view_count: 320,
    views: 320,
    created_at: '2025-02-01T00:00:00Z',
    updated_at: '2025-02-01T00:00:00Z',
    published_at: '2025-02-01T00:00:00Z',
  },
  {
    id: '3',
    title: 'Mastering TypeScript: Advanced Patterns',
    slug: 'typescript-advanced-patterns',
    excerpt:
      'Explore advanced TypeScript patterns including generics, decorators, and utility types to write better code.',
    content: 'Full content here...',
    cover_image: '',
    tags: ['typescript', 'javascript', 'patterns'],
    published: true,
    is_published: true,
    is_featured: false,
    read_time: 12,
    reading_time: 12,
    view_count: 180,
    views: 180,
    created_at: '2025-03-01T00:00:00Z',
    updated_at: '2025-03-01T00:00:00Z',
    published_at: '2025-03-01T00:00:00Z',
  },
  {
    id: '4',
    title: 'Building RESTful APIs with FastAPI',
    slug: 'restful-apis-fastapi',
    excerpt:
      'Complete guide to creating production-ready REST APIs using FastAPI, SQLAlchemy, and Pydantic.',
    content: 'Full content here...',
    cover_image: '',
    tags: ['fastapi', 'python', 'api'],
    published: true,
    is_published: true,
    is_featured: false,
    read_time: 8,
    reading_time: 8,
    view_count: 210,
    views: 210,
    created_at: '2025-04-01T00:00:00Z',
    updated_at: '2025-04-01T00:00:00Z',
    published_at: '2025-04-01T00:00:00Z',
  },
  {
    id: '5',
    title: 'React Performance Optimization Techniques',
    slug: 'react-performance-optimization',
    excerpt:
      'Learn proven techniques to optimize your React applications for better performance and user experience.',
    content: 'Full content here...',
    cover_image: '',
    tags: ['react', 'performance', 'optimization'],
    published: true,
    is_published: true,
    is_featured: true,
    read_time: 7,
    reading_time: 7,
    view_count: 290,
    views: 290,
    created_at: '2025-05-01T00:00:00Z',
    updated_at: '2025-05-01T00:00:00Z',
    published_at: '2025-05-01T00:00:00Z',
  },
  {
    id: '6',
    title: 'Introduction to Machine Learning with Python',
    slug: 'intro-machine-learning-python',
    excerpt:
      'Start your journey in machine learning with Python, scikit-learn, and practical examples.',
    content: 'Full content here...',
    cover_image: '',
    tags: ['python', 'machine-learning', 'ai'],
    published: true,
    is_published: true,
    is_featured: false,
    read_time: 20,
    reading_time: 20,
    view_count: 450,
    views: 450,
    created_at: '2025-06-01T00:00:00Z',
    updated_at: '2025-06-01T00:00:00Z',
    published_at: '2025-06-01T00:00:00Z',
  },
];
