import { Project, Technology } from '../services/types';

const sampleTechnologies = (...names: string[]): Technology[] =>
  names.map((name, index) => ({
    id: `${name}-${index}`,
    name,
    slug: name.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
  } as Technology));

export const mockProjects: Project[] = [
  {
    id: 'mock-1',
    title: 'Personal Portfolio Platform',
    slug: 'personal-portfolio-platform',
    description:
      'A full-stack portfolio site with FastAPI backend, React frontend, Supabase storage, and automated content syncing.',
    short_description: 'Full-stack portfolio platform',
    cover_image: '',
    demo_url: 'https://example.com/demo/portfolio',
    github_url: 'https://github.com/example/portfolio',
    technologies: sampleTechnologies('FastAPI', 'React', 'Supabase', 'Redis'),
    featured: true,
    display_order: 1,
    created_at: new Date('2025-02-10').toISOString(),
    updated_at: new Date('2025-05-12').toISOString(),
  },
  {
    id: 'mock-2',
    title: 'AI-Powered Resume Parser',
    slug: 'ai-resume-parser',
    description:
      'Applicant tracking pipeline that parses resumes, extracts entities, and matches candidates to roles using NLP.',
    short_description: 'Automated resume analysis',
    cover_image: '',
    demo_url: '',
    github_url: 'https://github.com/example/resume-parser',
    technologies: sampleTechnologies('Python', 'FastAPI', 'PostgreSQL', 'spaCy'),
    featured: false,
    display_order: 2,
    created_at: new Date('2024-11-18').toISOString(),
    updated_at: new Date('2025-03-05').toISOString(),
  },
  {
    id: 'mock-3',
    title: 'Realtime Collaboration Board',
    slug: 'realtime-collaboration-board',
    description:
      'Kanban-style collaboration board with live updates, optimistic UI, and role-based moderation tools.',
    short_description: 'Realtime Kanban board',
    cover_image: '',
    demo_url: '',
    github_url: 'https://github.com/example/realtime-board',
    technologies: sampleTechnologies('React', 'Tailwind CSS', 'Supabase', 'WebSockets'),
    featured: true,
    display_order: 3,
    created_at: new Date('2024-08-01').toISOString(),
    updated_at: new Date('2025-01-22').toISOString(),
  },
  {
    id: 'mock-4',
    title: 'Developer Blog Engine',
    slug: 'developer-blog-engine',
    description:
      'Markdown-powered blog engine with GitHub integration, webhooks, and scheduled publishing.',
    short_description: 'Static-like blog engine',
    cover_image: '',
    demo_url: 'https://example.com/blog',
    github_url: '',
    technologies: sampleTechnologies('FastAPI', 'Markdown', 'GitHub Actions'),
    featured: false,
    display_order: 4,
    created_at: new Date('2024-06-15').toISOString(),
    updated_at: new Date('2025-04-30').toISOString(),
  },
  {
    id: 'mock-5',
    title: 'Analytics Dashboard',
    slug: 'analytics-dashboard',
    description:
      'Interactive analytics dashboard with multi-dimensional filters, responsive charts, and cached API responses.',
    short_description: 'Interactive analytics UI',
    cover_image: '',
    demo_url: '',
    github_url: 'https://github.com/example/analytics-dashboard',
    technologies: sampleTechnologies('React', 'TypeScript', 'D3.js'),
    featured: false,
    display_order: 5,
    created_at: new Date('2024-04-02').toISOString(),
    updated_at: new Date('2025-02-12').toISOString(),
  },
  {
    id: 'mock-6',
    title: 'Email Automation Service',
    slug: 'email-automation-service',
    description:
      'Email automation microservice handling transactional notifications, batching, and bounce tracking.',
    short_description: 'Email automation microservice',
    cover_image: '',
    demo_url: '',
    github_url: 'https://github.com/example/email-automation',
    technologies: sampleTechnologies('FastAPI', 'Redis', 'Celery'),
    featured: false,
    display_order: 6,
    created_at: new Date('2024-01-10').toISOString(),
    updated_at: new Date('2025-02-27').toISOString(),
  },
];
